name: ROS 2 Jazzy CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format-check:
    runs-on: ubuntu-24.04
    container:
      image: osrf/ros:jazzy-desktop
      options: --user root
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format
      - name: Check for incorrect file extensions
        shell: bash
        run: |
          bash ./scripts/check_extensions.sh
      - name: Check formatting
        shell: bash
        run: |
          bash ./scripts/check_formatting.sh

  build-and-test-ubuntu:
    needs: format-check
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        arch: [amd64, arm64, arm32]
    runs-on: ${{ matrix.os }}
    container:
      image: osrf/ros:jazzy-desktop
      options: --user root
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install build tools
        run: |
          apt-get update
          apt-get install -y python3-colcon-common-extensions python3-rosdep python3-vcstool git \
            libboost-all-dev libgmock-dev python3-pip ros-jazzy-ament-copyright

      - name: Update rosdep database
        run: rosdep update || true

      - name: Install dependencies
        run: |
          rosdep install --from-paths . --ignore-src -r -y

      - name: Build project
        shell: bash
        run: |
          . /opt/ros/jazzy/setup.bash
          colcon build --cmake-args -DBUILD_TESTING=On

      - name: Run tests
        shell: bash
        run: |
          . /opt/ros/jazzy/setup.bash
          . install/setup.bash
          colcon test --event-handlers console_cohesion+
          colcon test-result

      - name: Upload test results
        if: ${{ !env.ACT && always() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-results-ubuntu-${{ matrix.arch }}
          path: build/ros2_test_framework_examples/test_results